// Code generated by "stringer -type ReplicaRole"; DO NOT EDIT.

package FabricEmu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReplicaRoleUnknown-0]
	_ = x[ReplicaRoleNone-1]
	_ = x[ReplicaRoleIdle-2]
	_ = x[ReplicaRoleSecondary-3]
	_ = x[ReplicaRolePrimary-4]
	_ = x[ReplicaRoleIdleAuxiliary-5]
	_ = x[ReplicaRoleAuxiliary-6]
	_ = x[ReplicaRolePrimaryAuxiliary-7]
}

const _ReplicaRole_name = "ReplicaRoleUnknownReplicaRoleNoneReplicaRoleIdleReplicaRoleSecondaryReplicaRolePrimaryReplicaRoleIdleAuxiliaryReplicaRoleAuxiliaryReplicaRolePrimaryAuxiliary"

var _ReplicaRole_index = [...]uint8{0, 18, 33, 48, 68, 86, 110, 130, 157}

func (i ReplicaRole) String() string {
	if i < 0 || i >= ReplicaRole(len(_ReplicaRole_index)-1) {
		return "ReplicaRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReplicaRole_name[_ReplicaRole_index[i]:_ReplicaRole_index[i+1]]
}
